apiVersion: apps/v1

kind: Deployment

metadata:

  name: api-deployment

  labels:

    app: api-app

spec:

  replicas: 3

  selector:

    matchLabels:

      app: api-app

  template:

    metadata:

      labels:

        app: api-app

    spec:

      containers:

      - name: api-app

        image: apiservicerg.azurecr.io/api-app

        ports:

        - containerPort: 5001
      imagePullSecrets:
       - name: apicred
