apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service

    spec:
      containers:
        - name: api-service
          image: apiservicerg.azurecr.io/api-app:latest
          imagePullPolicy: Always
      #imagePullSecrets:
       # - name: default-token-lrs7h
    
