name: eks pipeline

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

env:
  AWS_REGION: us-east-1                                         # set this to your preferred AWS region, e.g. us-west-1

jobs: 
  notify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
#         uses: actions/checkout@v2
        uses: actions/checkout@v3

      - name: Install kubectl
#         uses: azure/setup-kubectl@v1
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27'
        id: install
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ env.AWS_REGION }}
              
      - name: Update kube config
        run: aws eks update-kubeconfig --region us-east-1 --name testing
              
      - name: Deploy image to eks
        run: |
          kubectl delete deploy app -n myapp
          kubectl apply -f Deployment/deployment1.yaml
          
          
          
          
          