name: Build

env:
  REGISTRY: ghcr.io
  IMAGE: ${{ github.repository }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push-image:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write

      steps:
       - uses: actions/checkout@v3
       - name: Set up Python
         uses: actions/setup-python@v3
         with:
          python-version: '3.11'

       - name: Install dependencies
         run: |
          python -m pip install --upgrade pip
          pip install build

#        - name: Set up Docker Buildx
#          uses: docker/setup-buildx-action@v1

#        - name: Login to GitHub Container Registry
#          uses: ./
#          with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}

       - name: Log in to the Container registry
         uses: docker/login-action@v1
         with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

       - name: Build and publish container image with tag
         uses: docker/build-push-action@v2
         with:
              push: true
              context: .
              file: ./Dockerfile
              tags: ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest